title: Blog
description: Blog personal tryn0

url: http://github.com/tryn0
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Inicio
    url: /index.html
  - title: Acerca
    url: /about
  - title: Contactar
    url: /contact

social:
  github: tryn0
