title: Blog
description: Blog personal tryn0

url: http://github.com/tryn0
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Inicio
    url: /index.html
  - title: Acerca
    url: /about
  - title: Contactar
    url: /contact

social:
  github: tryn0
  rss: "" #Añadido para que active el la opción feed en el footer, pie de página, así pondrá la imagen de rss y link para el feed
  email: vkae@live.com
  #facebook:
